untitled/Amara/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mall/', include('mall.urls')),
]

untitled/mall/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'mall'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.UserFormView.as_view(), name='signup'),
    url(r'^login/$', auth_views.login, {'template_name': 'mall/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/mall'}, name='logout'),
    url(r'^personal/$', views.tr, name='personal')
    ]

untitled/mall/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.core.validators import RegexValidator


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, last_name, password, is_staff, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.is_staff = is_staff
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, first_name, last_name, password, **extra_fields)

    def create_superuser(self, email, first_name, last_name, password, **extra_fields):
        is_staff = True
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, first_name, last_name, password, is_staff, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', unique=True)
    first_name = models.CharField('first name', max_length=30)
    last_name = models.CharField('last name', max_length=30)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)
    is_active = models.BooleanField('active', default=True)
    is_staff = models.BooleanField(default=False)
    phone_regex = RegexValidator(regex=r'^\+?234?\d{10}$',
                                 message="Phone number must be in the format: '+234...'. Up to 13 digits allowed.")
    telephone = models.CharField(validators=[phone_regex], blank=True, max_length=14)  # validators should be a list
    address1 = models.CharField(max_length=1000, blank=True)
    address2 = models.CharField(max_length=1000, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Owner(User):
    owner_image = models.ImageField(upload_to='avatar/%Y/%m/%d')


class Store (models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    store_name = models.CharField(max_length= 30)
    store_logo = models.ImageField(upload_to= 'store-logo/%Y/%m/%d')
    address1 = models.CharField(max_length=100, blank=False)
    address2 = models.CharField(max_length=100, blank=True)
    telephone = models.IntegerField()
    email= models.EmailField(max_length=60)


class Item (models.Model):
    item_mame = models.CharField(max_length= 30)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    price= models.IntegerField()
    details = models.CharField(max_length=1000)
    photo1 = models.ImageField(upload_to= 'item/%Y/%m/%d', blank=False)
    photo2 = models.ImageField(upload_to='item/%Y/%m/%d', blank=True)
    photo3 = models.ImageField(upload_to='item/%Y/%m/%d', blank=True)

untitled/mall/forms.py
from django import forms
from .models import User


class UserForm (forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password', 'telephone', 'address1']


# class LoginForm (forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)
#
#     class Meta:
#         model = User
#         fields = ['email', 'password']

untitled/mall/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from .models import User


# Create your views here.
class UserFormView(View):
    form_class = UserForm
    template_name = 'mall/signup.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            telephone = form.cleaned_data['telephone']
            address1 = form.cleaned_data['address1']
            user.set_password(password)
            user.save()

            user = authenticate(email=email, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    context = {'user':user}
                    return render(request, 'mall/index.html', context)

        return render(request, self.template_name, {'form':form})


def index(request):
    template_name = 'mall/index.html'
    return render(request, template_name )


def tr(request):
    template_name = 'mall/personal.html'
    return render(request, template_name)

untitled/mall/templates/mall/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Amara's Wall |
        {% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'mall/stylesheet/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'mall/stylesheet/base.css' %}" />
    </head>
    <body>
        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}
    </body>
</html>

untitled/mall/templates/mall/index.html
{% extends "mall/base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block content %}
    {% load static %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#"><img src= "{% static 'mall/pictures/icons/home.png' %}" />HOME<span class="sr-only">(current)</span></a></li>
                <li><a href="#"><img style="height: 32px; width: 45px"; src= "{% static 'mall/pictures/icons/video.png' %}"/>INTRO VIDEOS</a></li>
            </ul>

            <div style="display: inline; position: relative; left:400px;">
                <a href=""><img style="height:50px; width: 70px;" src="{% static 'mall/pictures/icons/logo.png' %}"></a>
            </div>
            <ul id="right" class="nav navbar-nav" style="float:right">
                <li><a href="#"><img src= "{% static 'mall/pictures/icons/store.png' %}" />STORES AND BRANDS<span class="sr-only">(current)</span></a></li>
                <li id="signup"><a href="{% url 'mall:signup' %}" ><img src= "{% static 'mall/pictures/icons/pen.png' %}" />SIGN UP</a></li>
            </ul>
        </div>
    </nav>

    <p>Welcome {{ user.email }} !!!</p>
    <a href="{% url 'mall:logout' %}">Logout</a>
{% endblock %}

untitled/mall/templates/mall/login.html
{% extends 'mall/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Alright</button>
  </form>
{% endblock %}

untitled/mall/templates/mall/personal.html
{% extends "mall/base.html" %}
{% block content %}hey everybody{% endblock %}

untitled/mall/templates/mall/signup.html
{% extends 'mall/base.html' %}
{% block content %}
    <form method="post" action="{% url 'mall:signup' %}">{% csrf_token %}
        <table border="0">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Register" />
    </form>
    <a href="{% url 'mall:login' %}">Login</a>
    <!--<div class="row">
        <div class="col-md-6">
            <h1>Sign Up </h1>
            <form action="{f% url 'mall:signup' %}" method="post">
                {f% csrf_token %}

                <label for="first_name">Firstname: </label>
                <input name="first_name" id="first_name" type="text"/>

                <label for="last_name">Lastname: </label>
                <input name="last_name" id="last_name" type="text"/>

                <label for="email">Email: </label>
                <input name="email" id="email" type="email"/>

                <label for="password">Password: </label>
                <input name="password" id="password" type="password"/>


                <label for="telephone">Telephone: </label>
                <input name="telephone" id="telephone" type="tel"/>

                <label for="address">Address: </label>
                <input name="address" id="address" type="text"/>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </form>
        </div>
        <div class="col-md-6"></div>
    </div>-->
{% endblock %}